"""
This module was autogenerated by gale.
"""
import pathlib

import pygame

from gale import frames
from gale import input_handler

input_handler.InputHandler.set_keyboard_action(input_handler.KEY_ESCAPE, 'quit')
input_handler.InputHandler.set_keyboard_action(input_handler.KEY_RETURN, "enter")
input_handler.InputHandler.set_keyboard_action(input_handler.KEY_RIGHT, "move_right")
input_handler.InputHandler.set_keyboard_action(input_handler.KEY_LEFT, "move_left")

# Size we want to emulate
VIRTUAL_WIDTH = 320
VIRTUAL_HEIGHT = 180

# Size of our actual window
WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

BASE_DIR = pathlib.Path(__file__).parent

# Register your textures from the graphics folder, for instance:
background_image = pygame.image.load(BASE_DIR / "assets" / "graphics" / "background.png")
background_image = pygame.transform.scale(background_image, (VIRTUAL_WIDTH, VIRTUAL_HEIGHT))

TEXTURES = {
    'background': background_image,
    'logo': pygame.image.load(BASE_DIR / "assets" / "graphics" / "logo.png"),
    'play_button': pygame.image.load(BASE_DIR/ "assets"/"graphics"/"play.png"),
    'instructions_button': pygame.image.load(BASE_DIR/ "assets"/"graphics"/"instructions.png"),
    'quit_button': pygame.image.load(BASE_DIR/ "assets"/"graphics"/"quit.png")

}

# Register your frames, for instance:
# FRAMES = {
#     'my_frames': frames.generate_frames(TEXTURES['my_texture'], 16, 16)
# }
FRAMES = {}

pygame.mixer.init()

# Register your sound from the sounds folder, for instance:
# SOUNDS = {
#     'my_sound': pygame.mixer.Sound(BASE_DIR / "assets"  / "sounds" / "my_sound.wav"),
# }
SOUNDS = {}

pygame.font.init()

# Register your fonts from the fonts folder, for instance:
FONTS = {
    'large': pygame.font.Font(BASE_DIR / "assets"  / "fonts" / "EagleLake-Regular.ttf", 12),
    'start_menu': pygame.font.Font(BASE_DIR / "assets"  / "fonts" / "EagleLake-Regular.ttf", 6)
}
